# Name of your site (displayed in the header)
title: Gilberto Velazquez Martinez
name: Gilberto Velazquez Martinez
twitter_username: tierbolg

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://tierbolg.wordpress.com/
 - title: GitHub
   url: https://github.com/tierbolg
 - title: LinkedIn
   url: https://www.linkedin.com/in/gilberto-vel%C3%A1zquez-mart%C3%ADnez-a599573a/

#Any buzzword skills you want to include
skills:
 - Scrum Master
 - Spring MVC/Boot/Security
 - JAVA
 - SQL
 - API design
 - REST
 - .NET Core
 - Mongo
 - Microservices
 - Reddis
 - Docker
 - Jenkins
 - Project Management
 - Technical Architecture
 - Machine Learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Technical Leader
   #start: 2017-09
   start: 2017
   end: Ongoing
   employer: HCL
   description: Technical Leader in charge of deployments, new requeriments and automatization projects related with communications backends for Mexico and Latin America. Assigned directly with Nokia
 - title: Senior Consulting
   #start: 2016-03
   start: 2016
   end: 2017
   employer: Deloitte
   description: Coordinator of projects in the area of ​​information technology, responsible for managing multidisciplinary work teams, budget management, quotations, propose solutions to the client that exceed their expectations with high standards of quality, architecture and security.
 - title: Senior Developer
   #start: 2014-01
   start: 2014
   end: 2016
   employer: Gemalto
   description: Working as a senior developer, I worked closely with the Research and Development division, champion expertise in Mercurial, JAVA, Oracle, Weblogic, Spring & Bash scripts. Promoted from Mexico to Singapore, working directly with teams in Asia, Europe, Canada & Brazil
 - title: Professional in technology
   #start: 2014-03
   start: 2009
   end: 2014
   employer: Federal Institute of Elections - Mexican Government
   description: Working on a range of functional and technical roles, automate and control 150 linux servers with several distributions like gentoo, debian and Oracle, manage IBM backup robot, configure and admin 450 Windows Servers using active directory. Man in charge of the acoustic fingerprint, an algorithm used for detect politian commercials in real time for radio and television

#Education is required
education:
 - level: Electronic Engineer
   date: 2010
   subject: Use of a hybrid method for the identification of disturbed fingerprints with a high level of noise
   school: National Autonomous University of Mexico

#List of interesting Github repo/projects to include - optional
github:
 - Tierbolg/Tierbolg.github.io
 #- robhinds/ElasticSearchGradle
 - Tierbolg/ResourcesCalculator
 - Tierbolg/SpringMVC
#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: http://stackoverflow.com/users/258813/rhinds
#   flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
  I am an engineer with almost 10 years of experience working in technology. I have primarily worked  as a server admin, facing many problems related to database synchronization, data replica, manage of roles, permissions, concurrence witha pplications and security. My obsession for automate tasks and be more productive give me the chance to be in charge of projects related to working in real time, with thousands of clients around my country. After that, I have worked across a broad range of technologies thereon Java, .NET, SQL, Javascript, Node, Mongo and most recently .NET Core and Spring. As well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of javascript technologies over the years, through jQuery.
  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code. I prefeer estructured methodologies like TDD, because give you more confident deliveries
  I have worked in large scale consultancy roles across Europe, Asia and Latin America, and the most satisfying thing has been to teach my team the technology, best practices and be disruptive, because Agile metodologies like Scrum if are planned are incredible powerful.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, Bash and Security, JPA in addition to others. <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used Azure for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of Azure solutions, including Active Directory, App Services, Containers, Azure Cosmos and SQL DAtabases<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, Angular, HTML5, Ajax, JSON, Rest Clients. <br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, Octopus, Team Foundation, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: tierbolg@outlook.com
  facebook:
  flickr:
  github: tierbolg.github.io
  instagram:
  linkedin: https://www.linkedin.com/in/gilberto-vel%C3%A1zquez-mart%C3%ADnez-a599573a/
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: tierbolg
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
